export const keywords = [
  "altana budowa",
  "altana do ogrodu drewniana",
  "altana drewniana do ogrodu",
  "altana drewniana konstrukcja",
  "altana drewniana nowoczesna",
  "altana drewniana przy domu",
  "altana drewniana przydomowa",
  "altana nowoczesna",
  "altana nowoczesna drewniana",
  "altana nowoczesna ogrodowa",
  "altana nowoczesna przy domu",
  "altana ogrodowa",
  "altana ogrodowa budowa",
  "altana ogrodowa drewniana",
  "altana z drewna",
  "altanka ogrodowa",
  "altanki ogrodowe",
  "altany drewniane",
  "altany drewniane ogrodowe",
  "altany ogrodowe",
  "altany ogrodowe drewniane",
  "altany ogrodowe nowoczesne",
  "budowa altany ogrodowej",
  "drewniana altana",
  "drewniana altana ogrodowa",
  "drewniane altany ogrodowe",
  "jak zrobić pergole",
  "jak zrobić pergole drewniane",
  "jak zrobić pergole ogrodowe",
  "nowoczesna altana",
  "nowoczesna altana ogrodowa",
  "nowoczesne altany",
  "nowoczesne altany drewniane",
  "nowoczesne altany ogrodowe",
  "nowoczesne altany ogrodowe drewniane",
  "pergola altana",
  "zabudowa altany",
]
